
services:

  postgres:
    image: postgres:17
    container_name: op-postgres
    environment:
      POSTGRES_DB: op_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
volumes: 
  postgres_data: